
[settings]

	[settings.general]
		"mvp++" = false
		rank_gifting = false
		welcome_back_message = "{h/} Welcome Back {username}! {dj}"
		toggle = true

[custom_users]

	[custom_users.user_1]
		welcome_back_message = "Welcome back qt Femboy!! {dj}"
		username = "FemboyDark"

